# Autogenerated file
def render(gps):
    yield """<div>
    <table class=\"center\">
        <caption><b>Status</b></caption>
        </tr>
        <tr>
            <td style=\"text-align:right\">GPS:</td>
            <td style=\"text-align:left\">"""
    yield str(gps)
    yield """</td>
          </tr>
      </table> 
</div>"""
